export const storetypes = [
    { name: "Accessories Store", type: "Retail" },
    { name: "Antique Shop", type: "Retail" },
    { name: "Appliance Store", type: "Retail" },
    { name: "Art Supply Store", type: "Retail" },
    { name: "Bakery", type: "Food" },
    { name: "Bath and Body Shop", type: "Retail" },
    { name: "Bed and Breakfast", type: "Hospitality" },
    { name: "Bicycle Shop", type: "Retail" },
    { name: "Bookstore", type: "Retail" },
    { name: "Boutique", type: "Retail" },
    { name: "Bridal Shop", type: "Retail" },
    { name: "Camera Store", type: "Retail" },
    { name: "Candy Store", type: "Retail" },
    { name: "Car Dealership", type: "Automotive" },
    { name: "Carpet Store", type: "Retail" },
    { name: "Cell Phone Store", type: "Retail" },
    { name: "Children's Clothing Store", type: "Retail" },
    { name: "Chocolate Shop", type: "Retail" },
    { name: "Cigar Shop", type: "Retail" },
    { name: "Clothing Store", type: "Retail" },
    { name: "Coffee Shop", type: "Food" },
    { name: "Comic Book Store", type: "Retail" },
    { name: "Computer Store", type: "Retail" },
    { name: "Convenience Store", type: "Retail" },
    { name: "Craft Store", type: "Retail" },
    { name: "Department Store", type: "Retail" },
    { name: "Discount Store", type: "Retail" },
    { name: "Dollar Store", type: "Retail" },
    { name: "Drugstore", type: "Retail" },
    { name: "Electronic Store", type: "Retail" },
    { name: "Eyewear Store", type: "Retail" },
    { name: "Fabric Store", type: "Retail" },
    { name: "Farmers Market", type: "Retail" },
    { name: "Florist", type: "Retail" },
    { name: "Furniture Store", type: "Retail" },
    { name: "Game Store", type: "Retail" },
    { name: "Gift Shop", type: "Retail" },
    { name: "Gourmet Food Store", type: "Food" },
    { name: "Grocery Store", type: "Food" },
    { name: "Hardware Store", type: "Retail" },
    { name: "Hat Shop", type: "Retail" },
    { name: "Health Food Store", type: "Food" },
    { name: "Home Decor Store", type: "Retail" },
    { name: "Ice Cream Shop", type: "Food" },
    { name: "Jewelry Store", type: "Retail" },
    { name: "Kitchen Supply Store", type: "Retail" },
    { name: "Lingerie Store", type: "Retail" },
    { name: "Liquor Store", type: "Retail" },
    { name: "Luggage Store", type: "Retail" },
    { name: "Maternity Store", type: "Retail" },
    { name: "Meat Market", type: "Retail" },
    { name: "Medical Supply Store", type: "Retail" },
    { name: "Men's Clothing Store", type: "Retail" },
    { name: "Mobile Phone Store", type: "Retail" },
    { name: "Motorcycle Dealer", type: "Automotive" },
    { name: "Music Store", type: "Retail" },
    { name: "Nail Salon", type: "Beauty" },
    { name: "Office Supply Store", type: "Retail" },
    { name: "Outdoor Equipment Store", type: "Retail" },
    { name: "Paint Store", type: "Retail" },
    { name: "Pawn Shop", type: "Retail" },
    { name: "Pet Store", type: "Retail" },
    { name: "Pharmacy", type: "Retail" },
    { name: "Pizza Place", type: "Food" },
    { name: "Plumbing Supply Store", type: "Retail" },
    { name: "Popcorn Store", type: "Retail" },
    { name: "Pottery Store", type: "Retail" },
    { name: "Produce Market", type: "Retail" },
    { name: "Record Store", type: "Retail" },
    { name: "RV Dealer", type: "Automotive" },
    { name: "Salon", type: "Beauty" },
    { name: "Sandwich Shop", type: "Food" },
    { name: "Seafood Market", type: "Retail" },
    { name: "Shoe Store", type: "Retail" },
    { name: "Skate Shop", type: "Retail" },
    { name: "Ski Shop", type: "Retail" },
    { name: "Smoke Shop", type: "Retail" },
    { name: "Smoothie Shop", type: "Food" },
    { name: "Souvenir Shop", type: "Retail" },
    { name: "Sporting Goods Store", type: "Retail" },
    { name: "Stationery Store", type: "Retail" },
    { name: "Supermarket", type: "Food" },
    { name: "Surf Shop", type: "Retail" },
    { name: "Swimwear Store", type: "Retail" },
    { name: "Tea Shop", type: "Food" },
    { name: "Thrift Store", type: "Retail" },
    { name: "Tire Shop", type: "Automotive" },
    { name: "Toy Store", type: "Retail" },
    { name: "Travel Agency", type: "Service" },
    { name: "Used Car Dealer", type: "Automotive" },
    { name: "Vape Shop", type: "Retail" },
    { name: "Vegetarian Restaurant", type: "Food" },
    { name: "Video Game Store", type: "Retail" },
    { name: "Vintage Clothing Store", type: "Retail" },
    { name: "Wine Shop", type: "Retail" },
    { name: "Women's Clothing Store", type: "Retail" },
    { name: "Yarn Shop", type: "Retail" },
    { name: "Yoga Studio", type: "Fitness" },
    { name: "Zoo Gift Shop", type: "Retail" }
  ]
  